### ISSUE TITLE
/F CREATE 

### ISSUE THREAD

**Issue by NemanjaMAX** [Awzaw/FactionsPro#12]
I'm using github.com/TesseractTeam/Tesseract
ERROR:
> rca h f create Testing
[Tesseract] [22:08:59] CRITICAL> Unhandled exception executing command 'f create Testing' in f: Call to undefined function FactionsPro\ctype_alnum()
[Tesseract] [22:08:59] CRITICAL> Error: "Call to undefined function FactionsPro\ctype_alnum()" (EXCEPTION) in "/plugins/FactionsPro-master/src/FactionsPro/FactionCommands" at line 129

GITHUB.COM/PMMP/POCKETMINE-MP IS ****, TESSERACT IS BIG DADDY!

**Comment by NemanjaMAX** [comment]
R.I.P Project..

**Comment by Awzaw** [comment]
This repo has been moved here: https://github.com/poggit-orphanage/FactionsPro, or you can try the new beta https://github.com/poggit-orphanage/FactionsPro_1.4. Both are available as .phar download on Poggit https://poggit.pmmp.io/pi

**Comment by Awzaw** [comment]
If you have the same problem with the Poggit versions then your version of PHP must have been compiled with ctype disabled for some reason, in which case you'll need to recompile with --enable-ctype
