### ISSUE TITLE
Facname

### ISSUE THREAD

**Issue by SinlesFlyer376** [Awzaw/FactionsPro#2]
So do I just do {fac_name} on the server?

**Comment by Uniqulmuia** [comment]
in purechat config it needs ti be like this:

  Guest:
    chat: '{fac_name} &3&l{prefix}&e[Guest]&f&r {display_name} &7> {msg}'
    nametag: '{fac_name} &3&l{prefix}&e[Guest]&f&r {display_name}'

This is just an example, you can add it to your custom rank.

**Comment by SinlesFlyer376** [comment]
Well it didn't work at first until I set DefaultFaction to FactionsPro and now it works

**Comment by Chris-Prime** [comment]
Funny

**Comment by SinlesFlyer376** [comment]
...
