### ISSUE TITLE
/f create issue

### ISSUE THREAD

**Issue by RTGDaCoder** [Awzaw/FactionsPro#9]
Hi! I've been getting this /f create issue. Can you please look into this?

```
07.03 12:25:48 [Server] Server thread/CRITICAL Error: "Call to a member function hasProfanity() on null" (EXCEPTION) in "/FactionsPro_v1.3.5.AWZ.phar/src/FactionsPro/FactionMain" at line 320
07.03 12:25:48 [Server] Server thread/CRITICAL Unhandled exception executing command 'f create CakeClan' in f: Call to a member function hasProfanity() on null
```

**Comment by iChaoticSoldier** [comment]
May i see the hole code of your FactionMain.php? I dont think my pull request can fix it. Send me the FactionMain.php code in my email iChaoticSoldier@gmail.com let me see whats the problem on line 320. Maybe you modified line

**Comment by RTGDaCoder** [comment]
Same. I got it from this Repo

**Comment by iChaoticSoldier** [comment]
Did you modified the code?

**Comment by RTGDaCoder** [comment]
Nope... i'll get the error

**Comment by iChaoticSoldier** [comment]
Please take a lool at the pull request ive made i commented the error screen shog if its same as your error

**Comment by RTGDaCoder** [comment]
```
08.03 11:58:17 [Server] Server thread/CRITICAL Error: "Call to a member function hasProfanity() on null" (EXCEPTION) in "/FactionsPro_v1.3.7.phar/src/FactionsPro/FactionMain" at line 321
08.03 11:58:17 [Server] Server thread/CRITICAL Unhandled exception executing command 'f create hi' in f: Call to a member function hasProfanity() on null
```

**Comment by RTGDaCoder** [comment]
in-game: Unknown error occured

**Comment by iChaoticSoldier** [comment]
Okay, my pull request can fix it. If the error in game shows Unknown error occurred

**Comment by RTGDaCoder** [comment]
https://github.com/Awzaw/FactionsPro/blob/master/src/FactionsPro/FactionMain.php#L321

**Comment by RTGDaCoder** [comment]
@iChaoticSoldier Ok, [this](https://github.com/Awzaw/FactionsPro/pull/8/files) , isn't this related to ! it means if i can't find the word in the name... Can u prove us with in game command and also from console. You can simply use CMDSnooper to view the commands you've typed...

**Comment by iChaoticSoldier** [comment]
Oh i forgot you got the error from FactionMain.php i thought you only got error from ctype_alnum() which is kind of annoying in Create Section of the code

**Comment by iChaoticSoldier** [comment]
@RTGDaCoder i used a php compiler on pc and on android i used DroidEditPro

**Comment by RTGDaCoder** [comment]
Hmmm, @Awzaw this issue hasn't been solved yet!

**Comment by Awzaw** [comment]
Which version of AntiSpamPro are you using?

**Comment by Awzaw** [comment]
Btw I've moved this here: https://github.com/poggit-orphanage/FactionsPro
